### ISSUE TITLE
Lean 4 server crashing

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#260] opened 2022-05-25 02:27 UTC
Hey, I've just started using Lean 4 and often get the error:

`Client 1 quit with exit code 1 and signal 0`

when I start editing. Not sure if it's related to #203? Just wanted to ask if you've ever seen this and know what's up, if not LMK if there's any more info I can provide to help find the issue. I didn't see any output in `~/.cache/nvim/{log,lsp.log}`, though I could also try to get a core dump.

**Comment by Julian** [comment] 2022-05-25 02:49
I don't think I've seen this before but I've used Lean4 less recently -- what version are you on just to be sure? And nothing on stderr when this happens?

**Comment by rish987** [comment] 2022-05-25 03:13
`leanprover/lean4:nightly-2022-05-18` (sorry, that should have been the first thing I included here)

Yeah I don't see any other output, the server just silently fails. Since you haven't seen this it very well may be my problem, I'll try things within an isolated environment tomorrow and get back to you.

**Comment by gebner** [comment] 2022-05-25 15:14
This looks like your Lean installation is messed up a bit.  When you start lean from nvim, it runs `lean --server`, which in turns runs one `lean --worker` process per file.  The error means that these two processes come from different Lean versions.

**Comment by rish987** [comment] 2022-05-25 15:49
Aha, it's completion related. I'm using `nvim-cmp` and see a crash (with the watchdog error above) inconsistently when invoking completion and then entering a newline. Not sure where the error lies, but I guess I can do without completion for now until I have time to look deeper.

**Comment by Julian** [comment] 2022-06-27 15:59
I've now actually seen this (on `Lean (version 4.0.0, commit 3eeeca22e281, Release)`) where I got a notification that:

```
2022-06-27T11:57:27  WARN Client 1 quit with exit code 1 and signal 0
```

but nothing on stderr and nothing else in `:messages`. I was doing nothing in particular special while that happened (just editing some unremarkable structure).

It should be that this is an upstream issue though right, so we should probably take it there if/when we diagnose this.

**Comment by rish987** [comment] 2022-06-27 18:43
OK good to know, yes I can confirm that I'm still seeing crashes as well without autocompletion, but they've become much less frequent. Hopefully the problem with completion is related because it's pretty easy for me to reproduce.

**Comment by rish987** [comment] 2022-06-29 15:38
So I think this could be coupled with synchronization issues (i.e. the server not picking up changes correctly) which I've noticed as well. I suspect the issue is on the nvim side, will investigate.

**Comment by rish987** [comment] 2022-07-10 18:45
I've investigated a bit more into my config, and I think this has to do with runtime load triggering a timing-related synchronization issue. In my case, I had a line `require("luasnip.loaders.from_vscode").load()` that loaded a ton of snippets from the `friendly-snippets` plugin, and commenting that out made the issue disappear (and made my nvim instance run faster in general) -- that's not to say that it fixed the issue, it probably just made it much less likely to occur. I will investigate further.

**Comment by rish987** [comment] 2022-07-11 02:24
We're debouncing. It turns out that because [neovim flushes pending changes on every server request](https://github.com/neovim/neovim/blob/95c65a6b221fe6e1cf91e8322e7d7571dc511a71/runtime/lua/vim/lsp.lua#L1217), we're getting two `textDocument/didChange` notifications with the same version number due to an upstream bug. neovim/neovim#19314 should fix it!

**Comment by rish987** [comment] 2022-07-11 15:27
I _think_ we can close this now, my only concern is that @Julian saw crashes without the `Watchdog error: ...` stderr output. And I think I've had this as well much earlier on, but recently I've only been getting a crash along with that output, I wonder if it could have something to do with the toolchain? But then again it looks like [this line](https://github.com/leanprover/lean4/blob/17c2e6d529421850f1237636546599eb392cd252/src/Lean/Server/Watchdog.lean#L435-L436) has been there for quite a while. I'd say we should leave this open for a bit more just to see if there are any other random crashes.

**Comment by Julian** [comment] 2022-07-11 15:36
I think we're also seeing something similar to this in CI, but I haven't gotten a chance to debug (well done tracking this down!). But yeah clients in CI seem to just exit with no output, but only on neovim nightly, stable is fine, and nightly I can't reproduce locally even :/

**Comment by Julian** [comment] 2022-10-15 20:02
OK gonna close this *now* since I haven't seen it recently and whatever was happening in CI isn't happening anymore, but lemme know if someone still does see these.

**Closed by Julian** 2022-10-15 20:02 UTC
Labels: bug
