### ISSUE TITLE
Hover positions are incorrect for lines with multibyte characters

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#206] opened 2021-11-18 21:57 UTC
I'm about to head out for the evening, so this may be an easy fix, but the infoview seems to break totally if in Lean 3 I have a line like:

```lean
variables {𝔽 : Type*} {
```

Save that to a file, open it, and just append to the end of the line, and the traceback says:

```
Error detected while processing CursorMovedI Autocommands for "<buffer=1>":                                                                                                                     
E5108: Error executing lua /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:545: index out of range                                                                                    
stack traceback:                                                                                                                                                                                
        [C]: in function 'str_byteindex'                                                                                                                                                        
        /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:545: in function 'update_extmark'                                                                                             
        /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:531: in function 'set_position_params'                                                                                        
        /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:624: in function 'move'                                                                                                       
        /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:443: in function 'move_pin'                                                                                                   
        /Users/julian/Development/lean.nvim/lua/lean/infoview.lua:846: in function '__update'                                                                                                   
        [string ":lua"]:1: in main chunk                                                                                                                                                        
```

(This obviously occurs when that line is in the middle of a longer file as well, and persists, so it basically just breaks the infoview).

It's still odd to me to see anything talking about pin updating when no pins are being used -- it seems something is miscalculating a character (which may be an easy fix), but in general I'd love it if no pin updates occurred unless I try to use pins.

More generally we probably should wrap infoview update calls in `pcall` and catch any failures and render them into the infoview so at least they don't repeatedly disrupt typing.

**Comment by rish987** [comment] 2021-11-18 22:38
Hmm odd, I can't reproduce. To make sure, this happens when you have a file with just that text and you hit `A` to insert at the end? Could you perhaps `git bisect` this?

In the infoview code, I've treated the current position as a "current pin" that moves when you move your cursor. This simplifies the code by avoiding special cases and is how it is automatically updated on file progress notifications for example. Yeah this does suggest that we could have more nuance in not setting `end_col` when the extmark is hidden for example, but as you suggest it should be an easy fix, just not sure how to repro this atm...

**Comment by rish987** [comment] 2021-11-18 23:06
Aha, after updating my neovim to the latest master, I get this problem too. So I suspect that there was a breaking change of some kind upstream, will investigate soon.

**Comment by rish987** [comment] 2021-11-19 03:21
Just bisected to neovim/neovim#15907, will investigate in more detail tomorrow.

**Comment by Julian** [comment] 2021-11-19 03:58
Damn you are fast. Well done. I was expecting to have to look myself in the
morning, thanks for finding that!

**Comment by rish987** [comment] 2021-11-19 18:35
Okay so it seems like Lean uses UTF32 indices for LSP interactions (@gebner CMIIW) while neovim/neovim#15907 defaults to UTF16. This creates a host of other issues, for example on lines with muti-index UTF16 characters, hover request positioning is off on those lines after those characters.

If we're able to configure the server to accept UTF16 instead of UTF32 then we could make a fix to lspconfig and shove this under the rug for the time being. @gebner is this possible? ISTM that it isn't since the config [defaults to UTF16](https://github.com/neovim/neovim/blob/9ec4417afc072533ed2c6924323e9d885c52f6fe/runtime/lua/vim/lsp.lua#L263), and clearly the server hasn't acknowledged that...

Otherwise I think I'll work on a PR alternative to neovim/neovim#15997 that doesn't introduce a breaking change to `buf_request` so we can hopefully get this fixed faster. Then we'll just have to set `offset_encoding = utf32` in lspconfig.

**Comment by gebner** [comment] 2021-11-19 18:48
> Okay so it seems like Lean uses UTF32 indices for LSP interactions

Lean 4 uses UTF-16 on the LSP side.  (There's a translation layer to transform UTF-16 indices to codepoint indices.)

The Lean 3 language server wrapper indeed treats all LSP positions as UTF-32 indices (i.e., counting Unicode codepoints, which Lean does internally).  The vscode extension has the same mismatch, it results in interesting failure modes. :smile:  If there's a way to indicate UTF-32 on the server side, PRs are also welcome at https://github.com/leanprover/lean-client-js

**Comment by rish987** [comment] 2021-11-22 06:27
@gebner how hard would it be to make Lean 4 also support UTF32? There's [the documentation for clangd](https://clangd.llvm.org/extensions#utf-8-offsets) that specifies an `offsetEncoding`, and I reckon this would make things a bit faster on the server side. Then we could at least eventually unify our logic in #208.

(frankly I'm pissed off that Microsoft has saddled everyone with UTF16 for what I suspect is the purpose of making sure that their own editor is compatible with the most language servers, but I'll try to keep my own cynicism out of this 😬)

**Comment by gebner** [comment] 2021-11-22 09:23
> how hard would it be to make Lean 4 also support UTF32?

This question here is not how if it would be difficult, but rather if it would be desirable.  I don't have any interest in supporting multiple encodings on the server side.  The encoding stuff is already hairy enough as it is.  Adding more choices just means that there are more code paths that need to be tested, and even more edge cases that can break.

The standard says UTF-16 so we need to support it, everything else just adds potential for bugs.

> I'm pissed off that Microsoft has saddled everyone with UTF16

I'm also unhappy with the concrete choice of encoding in the standard, but realistically speaking there is no good choice here.  All of them require ugly conversions, but with UTF-16 it's at least obvious that things are broken...

You might think that Unicode codepoints are the obviously correct way to count characters, but of course they're not.  Take for example everybody's favorite variable name, `Z̖̪͕̝̱̝͍̰͉͑̾ͪ͗ͪ`.  In my terminal, that's one character.  But it's 15 Unicode codepoints (and 32 bytes of UTF-16).  And neovim handles it just fine (as one character).

If we were to adopt UTF-32 for indexing, then it would be easy to make the fallacious assumption that index = "number of characters on screen".  It would of course be correct *more often* than mixing up UTF-16 and UTF-32, but it's just as broken.

**Comment by rish987** [comment] 2021-11-22 17:08
Even with combining characters and the like, it still seems inherently ridiculous to translate to force clients to translate to a random optimization scheme they _don't even use_ rather than to the representation that UTF encodings were intended to be converted to. I know there's nothing we can do about it at this point but it's just so obvious that MS did this to give themselves a shortcut at everyone else's expense.

> I don't have any interest in supporting multiple encodings on the server side. The encoding stuff is already hairy enough as it is. Adding more choices just means that there are more code paths that need to be tested, and even more edge cases that can break.

If `clangd` and `rust-analyzer` found this worth doing, I don't see why Lean shouldn't. The code for these conversions should be fairly self-contained and easy to (perhaps FORMALLY) verify, right? And if it isn't, that's already something that needs to be fixed. I realize that this is probably something I'll have to PR myself if I want it, and I certainly hope to contribute to the server once I finish my thesis, so perhaps we can discuss this again in a few months.

**Comment by rish987** [comment] 2021-12-07 19:40
Reopening since we're still technically waiting on neovim/neovim#16382 (though it looks like this is going to be merged shortly).

**Comment by mjlbach** [comment] 2021-12-13 18:33
16382 is merged so you all should close this.

**Closed** 2021-12-13 18:44 UTC
Labels: bug

**Comment by rish987** [comment] 2021-12-14 04:50
@gebner quick question does the Lean 3 server also treat textDocument/didChange parameters as UTF-32?

If so I'm surprised we didn't notice any issues before since while investigating neovim/neovim#16624 it looks like the default is UTF-16.

**Comment by gebner** [comment] 2021-12-14 10:20
> quick question does the Lean 3 server also treat textDocument/didChange parameters as UTF-32?

No.  There are two programs here: neovim communicates with `lean-language-server`, which then in turn communicates with `lean --server`.

The `lean --server` pretends everything is UTF-32.  The `lean-language-server` pretends everything is UTF-16.  It's a beautiful mess! :smile: 

Fortunately the incremental `didChange` notifications are interpreted by `lean-language-server` as UTF-16, which it translates into full change synchronizations for `lean --server` (without positions).

All the other requests are passed through to `lean --server` without adjusting the position; which means that their positions are interpreted as UTF-32.

**Comment by rish987** [comment] 2021-12-14 14:14
> Fortunately the incremental `didChange` notifications are interpreted by `lean-language-server` as UTF-16, which it translates into full change synchronizations for `lean --server` (without positions).

From what I can tell [`lean-language-server` only supports `TextDocumentSyncKind.Full`](https://github.com/leanprover/lean-client-js/blob/87b1214dbabf55e8e3d04e22762f62242300f70d/lean-language-server/src/index.ts#L53), so the distinction between UTF-16 and UTF-32 doesn't even enter into it. Is this correct?

**Comment by gebner** [comment] 2021-12-14 14:28
> From what I can tell [`lean-language-server` only supports `TextDocumentSyncKind.Full`](https://github.com/leanprover/lean-client-js/blob/87b1214dbabf55e8e3d04e22762f62242300f70d/lean-language-server/src/index.ts#L53), so the distinction between UTF-16 and UTF-32 positions doesn't even enter into it. Is this correct?

You're right!

**Comment by rish987** [comment] 2021-12-14 14:33
In that case is VSCode 1-upping us in being able to do incremental syncs somehow? If so I can probably look into how to to support this from `lean-language-server`.

**Comment by gebner** [comment] 2021-12-14 14:35
No, Lean 3 doesn't do incremental sync at all.  (I just thought the javascript LSP library would simulate it.)
